# Generated by Django 5.2.8 on 2025-11-18 08:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('date', models.DateTimeField(db_index=True)),
                ('helga_id', models.IntegerField(default=0)),
                ('location', models.CharField()),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField()),
                ('helga_id', models.IntegerField(db_index=True, null=True)),
                ('elo', models.DecimalField(decimal_places=2, default=1500.0, max_digits=7)),
                ('active', models.BooleanField(db_index=True, default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('distance', models.IntegerField()),
                ('climb', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.course')),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('place', models.IntegerField()),
                ('time', models.TimeField(null=True)),
                ('status', models.CharField()),
                ('new_elo', models.DecimalField(decimal_places=2, default=1500.0, max_digits=7)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.ranking')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.runner')),
            ],
        ),
    ]
