# Generated by Django 5.2.8 on 2026-04-22 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('date', models.DateTimeField(db_index=True)),
                ('helga_id', models.IntegerField(default=0)),
                ('location', models.CharField()),
                ('status', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Runner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(db_index=True)),
                ('helga_id', models.IntegerField(db_index=True, null=True)),
                ('elo', models.DecimalField(db_index=True, decimal_places=2, default=1500.0, max_digits=7)),
                ('active', models.BooleanField(db_index=True, default=True)),
                ('number_of_valid_courses', models.PositiveIntegerField(db_index=True, default=0)),
                ('abso', models.BooleanField(db_index=True, default=False)),
                ('category', models.CharField(db_index=True, default='', max_length=5)),
                ('club', models.CharField(default='')),
                ('fede', models.CharField(default='')),
                ('nationality', models.CharField(default='')),
                ('sex', models.CharField(default='', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Ranking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField()),
                ('distance', models.IntegerField()),
                ('climb', models.IntegerField(null=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.course')),
            ],
        ),
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(db_index=True)),
                ('place', models.IntegerField()),
                ('time', models.TimeField(null=True)),
                ('status', models.CharField()),
                ('new_elo', models.DecimalField(decimal_places=2, default=1500.0, max_digits=7)),
                ('ranking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.ranking')),
                ('runner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.runner')),
                ('elo_diff', models.DecimalField(decimal_places=2, default=0.0, max_digits=7)),
                ('startnumber', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
