# Generated by Django 6.0.1 on 2026-04-24 08:35

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='helga_id',
            new_name='source_id',
        ),
        migrations.AddField(
            model_name='course',
            name='source',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'helga webres'), (2, 'liveresults.se'), (3, 'ffco cn')], default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='subtype',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'LD'), (2, 'MD'), (3, 'sprint')], default=0),
        ),
        migrations.AddField(
            model_name='course',
            name='type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'foot o'), (2, 'mtb o'), (3, 'ski o')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'to download'), (2, 'to process'), (3, 'done')], default=0),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2, 3])), name='elo_Course_status_CourseStatus'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', [0, 1, 2, 3])), name='elo_Course_source_Source'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('type__in', [0, 1, 2, 3])), name='elo_Course_type_CourseType'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('subtype__in', [0, 1, 2, 3])), name='elo_Course_subtype_CourseSubType'),
        ),
    ]
