# Generated by Django 6.0.7 on 2026-09-28 21:49

import django_enum.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0002_remove_result_runner_remove_runner_abso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='source',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'Helga Webres'), (2, 'liveresults.se'), (3, 'ffco cn'), (4, 'helga start')], default=0),
        ),
        migrations.AlterField(
            model_name='source',
            name='source_type',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'Helga Webres'), (2, 'liveresults.se'), (3, 'ffco cn'), (4, 'helga start')], default=0),
        ),
    ]
