# Generated by Django 6.0.1 on 2026-05-03 15:14

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0002_rename_helga_id_course_source_id_course_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='elo_Course_status_CourseStatus',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'to download'), (2, 'to import'), (3, 'to process'), (10, 'done')], default=0),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2, 3, 10])), name='elo_Course_status_CourseStatus'),
        ),
    ]
