# Generated by Django 6.0.4 on 2026-05-16 11:51

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0003_remove_course_elo_course_status_coursestatus_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='elo_Course_subtype_CourseSubType',
        ),
        migrations.AddField(
            model_name='runner',
            name='ffco_id',
            field=models.IntegerField(db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='subtype',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'LD'), (2, 'MD'), (3, 'sprint'), (4, 'night')], default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='new_elo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='runner',
            name='elo',
            field=models.DecimalField(db_index=True, decimal_places=2, default=1600.0, max_digits=7),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('subtype__in', [0, 1, 2, 3, 4])), name='elo_Course_subtype_CourseSubType'),
        ),
    ]
