# Generated by Django 6.0.7 on 2026-07-19 00:29

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0003_remove_course_elo_course_status_coursestatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starttime', models.TimeField(null=True)),
                ('startnumber', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='elo_Course_source_Source',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='elo_Course_status_CourseStatus',
        ),
        migrations.AlterField(
            model_name='course',
            name='source',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'helga webres'), (2, 'liveresults.se'), (3, 'ffco cn'), (4, 'helga start')], default=0),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'to download'), (2, 'to import'), (3, 'to process'), (9, 'future course'), (10, 'done')], default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='new_elo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='runner',
            name='elo',
            field=models.DecimalField(db_index=True, decimal_places=2, default=1600.0, max_digits=7),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2, 3, 9, 10])), name='elo_Course_status_CourseStatus'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', [0, 1, 2, 3, 4])), name='elo_Course_source_Source'),
        ),
        migrations.AddField(
            model_name='entry',
            name='ranking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.ranking'),
        ),
        migrations.AddField(
            model_name='entry',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elo.runner'),
        ),
    ]
