# Generated by Django 5.2.8 on 2025-12-16 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_result_startnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runner',
            name='fullname',
            field=models.CharField(db_index=True),
        ),
    ]
