# Generated by Django 6.0.1 on 2026-07-21 12:53

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_entry_remove_course_elo_course_source_source_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='elo_Course_status_CourseStatus',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'to download'), (2, 'to import'), (3, 'to process'), (9, 'future course'), (10, 'done'), (20, 'to delete')], default=0),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2, 3, 9, 10, 20])), name='elo_Course_status_CourseStatus'),
        ),
    ]
