# Generated by Django 6.0.4 on 2026-07-09 23:09

import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0004_remove_course_elo_course_subtype_coursesubtype_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='course',
            name='elo_Course_status_CourseStatus',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'to download'), (2, 'to import'), (3, 'to process'), (9, 'future course'), (10, 'done')], default=0),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2, 3, 9, 10])), name='elo_Course_status_CourseStatus'),
        ),
    ]
