# Generated by Django 6.0.1 on 2026-07-21 15:12

import django.db.models.deletion
import django_enum.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0005_remove_course_elo_course_status_coursestatus_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Affiliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fede', models.CharField()),
                ('club', models.CharField(db_index=True)),
                ('country', models.CharField(db_index=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_type', django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'helga webres'), (2, 'liveresults.se'), (3, 'ffco cn'), (4, 'helga start')], default=0)),
                ('ext_runner_id', models.IntegerField(db_index=True)),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='elo_Course_source_Source',
        ),
        migrations.RemoveConstraint(
            model_name='course',
            name='elo_Course_status_CourseStatus',
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=django_enum.fields.EnumPositiveSmallIntegerField(choices=[(0, 'unknown'), (1, 'to download'), (2, 'to import'), (3, 'to process'), (9, 'future course'), (10, 'done')], default=0),
        ),
        migrations.AlterField(
            model_name='result',
            name='runner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='elo.runner'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', [0, 1, 2, 3, 9, 10])), name='elo_Course_status_CourseStatus'),
        ),
        migrations.AddConstraint(
            model_name='course',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', [0, 1, 2, 3, 4])), name='elo_Course_source_SourceType'),
        ),
        migrations.AddField(
            model_name='affiliation',
            name='runner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elo.runner'),
        ),
        migrations.AddField(
            model_name='source',
            name='runner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='elo.runner'),
        ),
        migrations.AddConstraint(
            model_name='source',
            constraint=models.CheckConstraint(condition=models.Q(('source_type__in', [0, 1, 2, 3, 4])), name='elo_Source_source_type_SourceType'),
        ),
    ]
