# Generated by Django 6.0.1 on 2026-01-31 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0005_alter_runner_fullname'),
    ]

    operations = [
        migrations.AddField(
            model_name='runner',
            name='abso',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='runner',
            name='category',
            field=models.CharField(db_index=True, default='', max_length=5),
        ),
        migrations.AddField(
            model_name='runner',
            name='club',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='runner',
            name='fede',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='runner',
            name='nationality',
            field=models.CharField(default=''),
        ),
        migrations.AddField(
            model_name='runner',
            name='sex',
            field=models.CharField(default='', max_length=1),
        ),
    ]
