# Generated by Django 6.0.7 on 2026-09-16 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elo', '0007_result_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='fullname_in_source',
            field=models.CharField(db_index=True, null=True),
        ),
    ]
